---
  - hosts: webserver
    tasks:
      - name: Download Oracle-JDK
        get_url:
          url: "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"
          dest: /home/vagrant
          checksum: "sha256:3d1e8cc66f4fd77acef6093329d5dd95bd06e4a03926c52df794f311a0c093f8"
          headers: "Cookie: oraclelicense=accept-securebackup-cookie"

      - name: Install Oracle-JDK
        yum:
          name: /home/vagrant/jdk-8u131-linux-x64.rpm
        become: yes

      - name: Add repository
        become: yes
        yum_repository:
          name: go-server
          description: Add yum repository
          baseurl: https://download.gocd.io
          gpgkey: https://download.gocd.io/GOCD-GPG-KEY.asc
          gpgcheck: yes

      - name: Install GoCD
        become: yes
        yum: name=go-server-17.1.0
