Vagrant.configure(2) do |config|
  config.vm.box = "centos-6.7"
  config.vm.network 'private_network', ip:'192.168.33.30'
  config.vm.provider "virtualbox" do |v|
	v.customize ["modifyvm", :id, "--memory", 2048, "--cpus", 1]
	end
end
